include:
  - src/vue3-client/.gitlab-ci.yml

stages:
  - format
  - pages
  - define-tag
  - build
  - test
  - deploy-production

define-tag:
  stage: define-tag
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "TAG=${tag}" >> build.env
  artifacts:
    reports:
      dotenv: build.env

# From https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#buildah-example
build-vue-frontend:
  stage: build
  image: quay.io/buildah/stable
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but Buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
  before_script:
    # GitLab container registry credentials taken from the predefined CI/CD variables
    # to authenticate to the registry.
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah images
    - buildah build -t "$CI_REGISTRY_IMAGE${TAG}" -f Dockerfile-vue3 src
    - buildah images
    - buildah push "$CI_REGISTRY_IMAGE${TAG}"
  # rules:
  #   - exists:
  #       - src/Dockerfile-vue3
  #     when: always

build-backend:
  stage: build
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah images
    - buildah build -t "$CI_REGISTRY_IMAGE/bun-backend${TAG}" src/Nodejs-RestAPIs
    - buildah images
    - buildah push "$CI_REGISTRY_IMAGE/bun-backend${TAG}"

test-backend:
  stage: test
  image: docker
  script:
    - docker run -d --name backend-test $CI_REGISTRY_IMAGE/bun-backend:${TAG}
    - sleep 10 # wait for the backend to start
    - curl --fail http://localhost:3000/health || (docker logs backend-test && exit 1)
    - docker stop backend-test
    - docker rm backend-test


deploy-production:
  image: curlimages/curl
  stage: deploy-production
  script:
    - curl -X POST --fail https://portainer.hilton.rwth-aachen.de/api/webhooks/ee27c453-3826-40ce-bde7-1ae896e2d4a3

