version: '3'

services:
  build_api:
    build: src/Nodejs-RestAPIs
    container_name: api.orga.symposion.hilton.rwth-aachen.de
    ports:
      - "8080:8080"
    networks:
      - barplaner
  build_web:
    build: src/Vue.js-Client
    container_name: orga.symposion.hilton.rwth-aachen.de
    ports:
      - "4200:4200"
    networks:
      - barplaner
networks:
  barplaner:
    # use the bridge driver, but enable IPv6
    driver: bridge
